apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "golden-signal-app.name" . }}
  labels:
    {{- include "golden-signal-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "golden-signal-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "golden-signal-app.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: golden-signal-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: APP_TENANTS
              value: {{ .Values.app.cardinality.tenants | quote }}
            - name: APP_ROUTES
              value: {{ .Values.app.cardinality.routes | quote }}
            - name: APP_HIST_BUCKETS
              value: {{ .Values.app.cardinality.histBuckets | quote }}
            - name: APP_REGION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['topology.kubernetes.io/zone']
            - name: APP_VERSION
              value: {{ .Chart.AppVersion | quote }}
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: 1
